### ISSUE TITLE
dr_wav: potential dead-code, flagged by static Clang analyzer

### ISSUE THREAD

**Issue by kcgen** [mackron/dr_libs#158] opened 2020-11-10 19:52 UTC
![2020-11-10_11-37_1](https://user-images.githubusercontent.com/1557255/98725937-a358f400-234a-11eb-8d9d-d41bdc35cb0c.png)

Full report attached:

[clang-analysis-report.zip](https://github.com/mackron/dr_libs/files/5519836/clang-analysis-report.zip)

**Comment by mackron** [comment] 2020-11-11 08:00
Duplicate of https://github.com/mackron/dr_libs/issues/154

**Closed by mackron** 2020-11-11 08:00 UTC
Labels: duplicate
