### ISSUE TITLE
dr_wav loads half track on 2 channel file

### ISSUE THREAD

**Issue by luuksteitner** [mackron/dr_libs#47] opened 2019-04-01 13:39 UTC
When a wave file has two channels, dr_wav loads only haldf the file. The problem appears to be in dr_wav.h in the function drwav_get_bytes_per_pcm_frame in the following part:

drwav_uint32 bitsPerFrame = pWav->bitsPerSample / pWav->fmt.channels;

The no. of bits per sample should not be divided by the number of channels (IMHO). When I remove the division it does load correctly.

**Comment by mackron** [comment] 2019-04-02 07:24
bitsPerSample is per-sample, not the per-frame. What version of dr_wav are you using? The implementation of that function should look like this:
```c
static drwav_uint32 drwav_get_bytes_per_pcm_frame(drwav* pWav)
{
    // The number of bytes per frame is based on the bits per sample or the block align. We prioritize floor(bitsPerSample*channels/8), but if
    // this is zero or the bits per frame is not a multiple of 8 we need to fall back to the block align.
    drwav_uint32 bitsPerFrame = pWav->bitsPerSample * pWav->fmt.channels;
    drwav_uint32 bytesPerFrame = bitsPerFrame >> 3;
    if (bytesPerFrame == 0 || (bitsPerFrame & 0x7) != 0) {
        bytesPerFrame = pWav->fmt.blockAlign;
    }

    return bytesPerFrame;
}
```
I'm not seeing that line you mentioned and it's wrong in any case.

**Comment by luuksteitner** [comment] 2019-04-02 09:04
Sorry about that, it's "drwav_uint32 bitsPerFrame = pWav->bitsPerSample * pWav->fmt.channels;" I had mistakenly types an '/' in stead of '*', as I had already removed the part "* pWav->fmt.channels" to correct the function.

**Comment by mackron** [comment] 2019-04-02 09:33
How was this file wav file generated? I don't think it's correct. `pWav->bitsPerSample` is taken straight from the `fmt` chunk verbatim, and every reference I've read says that this is per-sample, not per-frame. I think your proposed change is working by coincidence rather than by design.

Here's some random references from a quick internet search (just look for references to "bits per sample" and you'll see how they're defined):
https://en.wikipedia.org/wiki/WAV
https://sharkysoft.com/jwave/docs/javadocs/lava/riff/wave/doc-files/riffwave-frameset.htm
https://joenord.com/audio-wav-file-format
http://www.topherlee.com/software/pcm-tut-wavformat.html

What are the values of `pWav->bitsPerSample` and `pWav->fmt.blockAlign` exactly?

How do other media players handle your file by the way?

**Comment by luuksteitner** [comment] 2019-04-02 09:45
I've tested this on many files from different sources. It loaded half the file on every file until I made this change. A few samples I just looked at:
16 bit, 2 channels, blockAlign: 4, 16 bit, 1 channel, blockAlign: 2, 32 bit, 2 channels, blockAlign 8.

It could be I'm doing something else wrong but right now I have no idea what that could be. If you don't have this problem, it's probably just me.

**Comment by mackron** [comment] 2019-04-02 09:46
How are you calling drwav_read_pcm_frames()?

**Comment by luuksteitner** [comment] 2019-04-02 09:47
pSampleData = (int32_t*)malloc((size_t)pWav->totalPCMFrameCount * pWav->channels * sizeof(int32_t));
drwav_read_pcm_frames_s32(pWav, pWav->totalPCMFrameCount, pSampleData);

**Comment by mackron** [comment] 2019-04-02 09:55
Everything looks fine. Are you forgetting to multiply `pWav->totalPCMFrameCount` by the channel count in some higher level logic somewhere?

I'm scratching my head a bit here because I've not had a bug report about this in recent memory and my test cases that compare against libsndfile are passing...

**Comment by mackron** [comment] 2019-04-02 10:18
What you could also try, just to verify whether or not the issue is with dr_wav, is to compile and run the simple_playback example from my audio library called [miniaudio](https://github.com/dr-soft/miniaudio). It's got no dependencies or anything so it'll only take a few minutes to compile and you just pass your input files to the command line to play them. If that works I'm doubting the issue is with dr_wav.

**Comment by luuksteitner** [comment] 2019-04-02 10:37
I'll have to look into this and get back to you later. For me this was a quick and dirty project to try some algorithms on some audio recordings and I was not planning to spend much time on it.

**Comment by mackron** [comment] 2019-05-04 05:41
I just tested with both my automated test program and with a listening test and have been unable to reproduce. One common issue I've seen is people forgetting to multiply the frame count with the channel count, so I would recommend checking that you're doing that properly. I'm going to go ahead and close this one, but if you feel like it's still definitely an issue with dr_wav feel free to reopen it or create a new one.

**Closed by mackron** 2019-05-04 05:41 UTC
