### ISSUE TITLE
Draft FLAC (dev) Undefined result of shift

### ISSUE THREAD

**Issue by kcgen** [mackron/dr_libs#123] opened 2020-03-29 04:55 UTC
![2020-03-28_21-48](https://user-images.githubusercontent.com/1557255/77840664-af3ad180-713e-11ea-842a-59e3c8d7137b.png)

Reported by Clang's static analyzer.

**Comment by mackron** [comment] 2020-03-30 07:45
I think this is a false positive. The only time that branch will be entered is if the number of bits being requested straddles the cache line which means a 64-bit shift will never occur. Also, in that function we will never request a number of bits more than 32, which is confirmed with the assert at the top of the function:

    DRFLAC_ASSERT(bitCount <= 32);

Since we can never request a number of bits larger than 32, we'll never be shifting by 64. I don't know how the static analyser is detecting this as such. Setting to wont fix.

**Comment by kcgen** [comment] 2020-03-30 15:49
`drflac_uint32 resultHi = (drflac_uint32)DRFLAC_CACHE_L1_SELECT_AND_SHIFT(bs, bitCountHi);`

If we shift by `bitCountHi`, and it's equal to:

`bitCountHi = ((sizeof((bs)->cache)*8) - (bs)->consumedBits)`

And the sizeof `drflac_cache_t cache` is 8 bytes if `drflac_uint64 drflac_cache_t`, then we've got:

`bitCountHi = 8 * 8 - (bs)->consumedBits`

So my guess is the analyzer is flagging the case if/when `consumedBits` is 0.

**Comment by mackron** [comment] 2020-03-30 21:43
If you scroll up you will see this branch:

    if (bitCount <= DRFLAC_CACHE_L1_BITS_REMAINING(bs)) {

If `consumedBits` is 0, `DRFLAC_CACHE_L1_BITS_REMAINING(bs)` will return 64 and will always be greater than `bitCount` which should never be more than 32 due to that assert.

What I might do is through an assert in there to try and silence this and make it a bit clearer. Reopening.

**Comment by mackron** [comment] 2020-03-30 22:04
OK, I've pushed a change which should hopefully clear this warning up, and at the very least make it a bit clearer for a human reading this later. Can you verify this one?

Commit: https://github.com/mackron/dr_libs/commit/df149b3fda66d9d0fd2d8e14e652ae3db44ad69d

**Comment by kcgen** [comment] 2020-03-30 22:23
Thanks for the explanation @mackron.  I'm surprised this is trigger Clang's analyzer; the logic here (although tricky for me as a reader because of all the macro-wrappers), wouldn't be hard to expand out for; and it doesn't seem any more involved that the other logic. 

Analysis is in progress - https://github.com/dreamer/dosbox-staging/actions/runs/66889629  Will know in a couple minutes.

(ps - when this new round of dr_flac and dr_mp3 versions are finalized, I will attribute the commits to you and squash these previous draft commits)

**Comment by kcgen** [comment] 2020-03-30 22:40
Hmm - it's still complaining about it: 
 - https://github.com/dreamer/dosbox-staging/suites/559515322/artifacts/3620711
 - Unzip (creates a `scan` directory), then launch `firefox index.html`

**Comment by mackron** [comment] 2020-03-30 22:53
My mistake. It was actually the `bitCountHi > 0` case that should have been asserted. Added that too.

Commit: https://github.com/mackron/dr_libs/commit/e9c6123fdee58a2d90fecf3fc586aa85f586db70

**Comment by kcgen** [comment] 2020-03-30 23:08
That solved it; thank you Dave!

**Closed** 2020-03-30 23:08 UTC
Labels: code improvement
